Eg smart string fix
softmatterlab/BRAPH-2-Matlab pull request #1206
Opened 2022-02-24 19:44 UTC by egolol

2022-02-25 14:01 UTC, annacanal commented
When I calculate Degree, and then I press show, I get an error. 
Also when pressing the analysis button to close all subfigures, degree stays there and an error jumps. Not sure if this was supposed to be fixed here

2022-02-25 14:12 UTC, annacanal commented
![Screenshot 2022-02-25 at 14 56 10](https://user-images.githubusercontent.com/31701548/155729457-226bbea1-a84a-4ac9-b17b-2e5d7091d5a5.png)
enlarge G is nicer. But the adjacency matrix plot and the graph button are overlapping with the table, I remember from yesterday they were not.

2022-02-25 14:14 UTC, annacanal commented
> When I calculate Degree, and then I press show, I get an error. Also when pressing the analysis button to close all subfigures, degree stays there and an error jumps. Not sure if this was supposed to be fixed here

`Error using matlab.ui.Figure/get
Invalid or deleted object.

Error in PPAnalyzeGroup_G/cb_measure_gui (line 1077)
		            tmp_gui = get(tmp_f, 'UserData');

Error in PPAnalyzeGroup_G/draw/cb_measure_plot_btn (line 833)
		            pr.cb_measure_gui();
 
Error while evaluating UIControl Callback.`

2022-02-25 14:22 UTC, annacanal commented
This error jumps when I successfully calculated a measure, showed it, and when I press Analysis to closes everything:

```
Error using Degree.existsTag (line 413)
BRAPH2:Degree:WrongInput The value PE is not a valid tag for Degree

Error in Degree.getPropProp (line 444)
				Degree.existsTag(tag);

Error in Element/get (line 845)
            prop = el.getPropProp(pointer);

Error in PPAnalyzeGroup_G/cb_hide (line 1375)
		            pe = gui.get('PE');

Error in GUI/cb_hide (line 1598)
		        pr.cb_hide()

Error in PPPipeline_PSDict/update (line 847)
		                            gui.cb_hide()

Error in PPPipeline_PSDict/draw/cb_pc_btn (line 766)
		        pr.update('Section', s, 'Code', c)
 
Error while evaluating UIControl Callback.
```

2022-02-25 14:27 UTC, annacanal commented
When I press 'C' at the Graph measure comparisons, this error jumps:
```

Unrecognized method, property, or field 'adj_plot_tgl_btn' for class 'PPCompareGroup_CPDict_WU'.

Error in PPCompareGroup_CPDict_WU/update (line 806)
		        set(pr.adj_plot_tgl_btn, 'Visible', 'on')

Error in PlotElement/update (line 1126)
		        pe.get('PR_DICT').getItem(prop).update()

Error in PlotProp/cb_button_calc (line 1152)
		    pe.update()

Error in PlotProp/draw/cb_button_calc (line 990)
		        pr.cb_button_calc()
 
Error while evaluating UIControl Callback.
```

2022-02-25 16:11 UTC, annacanal requested changes

2022-02-25 16:11 UTC, annacanal commented on braph2genesis/src/analysis/_PPAnalyzeGroup_G.gen.m
> +            'Position', [.79 .71 .2 .15], ...
'Position', [.79 **.77** .2 .15], ...
makes that the buttons have space with the table under

2022-02-25 16:11 UTC, annacanal commented on braph2genesis/src/analysis/_PPAnalyzeGroup_G.gen.m
> +            'Position', [.01 .71 .2 .15], ...
'Position', [.01 **.77** .2 .15], ...
makes that the buttons have space with the table under

2022-02-25 16:11 UTC, annacanal commented on braph2genesis/src/analysis/_PPAnalyzeGroup_G.gen.m
> +            'Position', [.23 .71 .2 .15], ...
'Position', [.23 **.77** .2 .15], ...
makes that the buttons have space with the table under

2022-02-28 09:01 UTC, egolol commented
solved

2022-02-28 10:10 UTC, c-yuwei commented
> ![Screenshot 2022-02-25 at 14 56 10](https://user-images.githubusercontent.com/31701548/155729457-226bbea1-a84a-4ac9-b17b-2e5d7091d5a5.png) enlarge G is nicer. But the adjacency matrix plot and the graph button are overlapping with the table, I remember from yesterday they were not.

solved

2022-02-28 10:10 UTC, c-yuwei commented
For @annacanal , please have Daniel's computer for testing the compiling issue
<img width="431" alt="image" src="https://user-images.githubusercontent.com/30530538/155964740-cb37bcd7-8128-495b-b61a-5071e53339f3.png">

2022-02-28 15:11 UTC, giovannivolpe approved these changes

2022-02-28 15:12 UTC, merged