Update NET prop
softmatterlab/BRAPH-2-Matlab pull request #1329
Opened 2022-04-18 10:48 UTC by c-yuwei

2022-04-18 18:07 UTC, c-yuwei commented
Please note 2 points
1. Toolbox Statistics and Machine Learning is used but not checked by function "BRAPH2.installed"
2. please check the bug correction in line 1453, Element.m

2022-04-19 05:25 UTC, giovannivolpe requested changes
make changes as discussed

2022-04-19 09:12 UTC, c-yuwei commented
> make changes as discussed

- [ ] change the probabilities to  0.01 from 0.1
- [ ] add nn prediction test in ETG
- [ ] add b2 save/load test in ETG

2022-04-19 11:23 UTC, giovannivolpe approved these changes

2022-04-19 11:23 UTC, merged