Jws revised issue1617
softmatterlab/BRAPH-2-Matlab pull request #1661
Opened 2023-10-18 11:56 UTC by JiaweiSun0512

2023-10-18 13:10 UTC, giovannivolpe requested changes
use m.get('NAME') instead of getting the file name

2023-10-18 13:10 UTC, giovannivolpe commented on braph2genesis/src/analysis/_AnalyzeGroupPP_G.gen.m
> +        set(gui_pfm, 'TITLE', ['Line plot: ' measure_fullname]);
use m.get('NAME') instead

2023-10-18 13:10 UTC, giovannivolpe commented on braph2genesis/src/analysis/_AnalyzeGroupPP_G.gen.m
> +                'TITLE', ['Brain plot: ' measure_fullname], ...
use m.get('NAME')

2023-10-21 12:12 UTC, giovannivolpe requested changes
In the case of the graph, it should be the graph LABEL prop, not the g_key (which the users cannot change)

2023-10-23 07:11 UTC, bzufiriaki approved these changes

2023-10-23 07:39 UTC, merged