nn and graphs
softmatterlab/BRAPH-2-Matlab pull request #1675
Opened 2023-10-20 11:11 UTC by egolol

2023-10-21 12:09 UTC, giovannivolpe requested changes
in general, also the NAME and DESCRIPTION props, and the description token need to be updated.

2023-10-25 16:21 UTC, c-yuwei requested changes

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultigraphBUD.gen.m
>   connectivity matrix binarized at different densities.
Should be:

In a binary undirected multigraph (MultigraphBUD) with fixed densities, all the layers consist of binary undirected graphs (GraphBU) derived from the same weighted connectivity matrix binarized at different densities.

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultigraphBUT.gen.m
>   weighted connectivity matrix binarized at different thresholds.
Same logic as in multigraphBUD

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultigraphBUD.gen.m
>   connectivity matrix binarized at different densities.
or leave out "(GraphBU)", to be consistent with the description in other graph elements.

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultigraphBUD.gen.m
> +'In a binary undirected multigraph with fixed densities, all the layers consist of binary undirected graphs (MultigraphBUD) derived from the same weighted connectivity matrix binarized at different d
Change according to the one in %%% ¡description!

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultigraphBUT.gen.m
> +'In a binary undirected multigraph with fixed thresholds, all the layers consist of binary undirected graphs (MultigraphBUT) derived from the same weighted connectivity matrix binarized at different
Same logic as in multigraphBUD

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultilayerBUD.gen.m
> + are those of binary undirected multilayer graphs derived from the same
Should be:

In a multilayer binary undirected **graph** with fixed densities (MultilayerBUD), ...

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultilayerBUD.gen.m
> +'In a multilayer binary undirected with fixed densities graph (MultilayerBUD), the layers are those of binary undirected multilayer graphs derived from the same weighted supra-adjacency matrix binari
same as top

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultilayerBUT.gen.m
> + are those of binary undirected multilayer graphs derived from the same
same as in MultilayerBUD

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultilayerBUT.gen.m
> +'In a multilayer binary undirected with fixed thresholds graph (MultilayerBUT), the layers are those of binary undirected multilayer graphs derived from the same weighted supra-adjacency matrix binar
same as in MultilayerBUD

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultiplexBUD.gen.m
> +In a binary undirected multiplex with fixed densities graph (MultiplexBUD), the layers are
same logic as in MultilayerBUD.
It should be:

In a **multiplex** binary undirected **graph** with fixed densities (MultiplexBUD), ...

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultiplexBUT.gen.m
> +In a binary undirected multiplex with fixed thresholds graph (MultiplexBUT), the layers are
same logic as in MultiplexBUD

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_MultiplexBUT.gen.m
> +'In a binary undirected multiplex with fixed thresholds graph (MultiplexBUT), the layers are those of binary undirected multiplex graphs derived from the same weighted supra-connectivity matrices bin
same logic as in MultiplexBUD

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMlBUD.gen.m
> +In an ordinal multilayer binary undirected with fixed densities graph (OrdMlBUD), layers
same logic as in MultiplexBUD

should be:
In an ordinal multilayer binary undirected **graph** with fixed densities (OrdMlBUD)

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMlBUD.gen.m
> +'In an ordinal multilayer binary undirected with fixed densities graph (OrdMlBUD), layers consist of binary undirected multilayer graphs derived from the same weighted supra-connectivity matrices bin
same

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMlBUT.gen.m
> +In an ordinal multilayer binary undirected with fixed thresholds graph (OrdMlBUT), layers
Same, should be

In an ordinal multilayer binary undirected **graph** with fixed thresholds (OrdMlBUT),

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMlBUT.gen.m
> +'In an ordinal multilayer binary undirected with fixed thresholds graph (OrdMlBUT), layers consist of binary undirected multilayer graphs derived from the same weighted supra-connectivity matrices bi
same

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMxBUD.gen.m
> +In an ordinal multiplex binary undirected with fixed densities graph (OrdMxBUD), the layers are
same

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMxBUD.gen.m
> -'In an ordinal binary undirected multiplex with fixed densities (BUD), the layers are those of binary undirected (BU) multiplex graphs derived from the same weighted supra-adjacency matrix binarized
same

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMxBUT.gen.m
> +In a ordinal multiplex binary undirected with fixed thresholds graphs (OrdMxBUT),
same

2023-10-25 16:21 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMxBUT.gen.m
> +'In a ordinal multiplex binary undirected with fixed threshold graph (OrdMxBUT),  all the layers consist of binary undirected multiplex graphs  derived from the same weighted supra-connectivity matri
same

2023-10-31 13:26 UTC, merged