CON create data directionality choice
softmatterlab/BRAPH-2-Matlab pull request #1677
Opened 2023-10-23 08:14 UTC by egolol

2023-10-24 13:14 UTC, annacanal requested changes
By default, it should create directed data, as the name indicates (create_data_COND_XLS), and the pipeline needs. So I do not understand why the option of undirected (for that there is already the file create_data_CON_XLS)

2023-10-24 13:14 UTC, annacanal commented on braph2genesis/pipelines/connectivity directed/create_data_COND_TXT.m
> +function create_data_COND_TXT(data_dir, random_seed, direction)
add also this file into braph2

2023-10-24 13:14 UTC, annacanal commented on braph2genesis/pipelines/connectivity directed/create_data_COND_XLS.m
> +function create_data_COND_XLS(data_dir, random_seed, direction)
add also this file into braph2

2023-10-24 13:14 UTC, annacanal commented on braph2genesis/pipelines/connectivity directed/example_CON_WD.m
> -    'FILE', [fileparts(which('SubjectCON')) filesep 'Example data CON XLS' filesep 'atlas.xlsx'], ...
update also this file in braph2

2023-10-24 13:14 UTC, annacanal commented on braph2genesis/pipelines/connectivity directed/create_data_COND_XLS.m
> +    gr1_name = 'CON_Group_1_XLS';
CON**D**_Group_1_XLS

2023-10-24 13:14 UTC, annacanal commented on braph2genesis/pipelines/connectivity directed/create_data_COND_XLS.m
> +    gr2_name = 'CON_Group_2_XLS';
CON**D**_Group_2_XLS

2023-10-24 13:14 UTC, annacanal commented on braph2genesis/pipelines/connectivity directed/create_data_COND_XLS.m
> +    data_dir = [fileparts(which('AnalyzeEnsemble_CON_WD')) filesep 'Example data CON XLS'];
should be maybe CON**D** XLS

2023-10-24 13:14 UTC, annacanal commented on braph2genesis/pipelines/connectivity directed/create_data_COND_XLS.m
> +    direction = 'undirected';
the default should be directed, that is why this file is called COND, no?

2023-10-24 13:23 UTC, egolol commented on braph2genesis/pipelines/connectivity directed/example_CON_WD.m
> -    'FILE', [fileparts(which('SubjectCON')) filesep 'Example data CON XLS' filesep 'atlas.xlsx'], ...
I understand that we now have to test in the exception folder, that's why it is only on genesis

2023-10-25 09:27 UTC, annacanal approved these changes

2023-11-03 13:40 UTC, merged