Comments Pipelines
softmatterlab/BRAPH-2-Matlab pull request #1683
Opened 2023-10-25 13:09 UTC by egolol

2023-10-27 08:36 UTC, bzufiriaki requested changes

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity directed/_AnalyzeEnsemble_CON_WD.gen.m
> +ELCLASS (constant, string) is the class of the ensenmble-based graph analysis using connectivity directed data.
"ensemble" --> check in all files

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity group_average/_AnalyzeGroup_CON_GA_WU.gen.m
> +ELCLASS (constant, string) is the class of the graph analysis with averaged connectivity data.
connectivity undirected data?

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity directed/_AnalyzeEnsemble_CON_WD.gen.m
> +NAME (constant, string) is the name of the ensenmble-based graph analysis using connectivity directed data.
ensemble

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity directed/_AnalyzeEnsemble_CON_WD.gen.m
> +DESCRIPTION (constant, string) is the description of the ensenmble-based graph analysis using connectivity directed data.
ensemble

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity directed/_AnalyzeEnsemble_CON_WD.gen.m
> +TEMPLATE (parameter, item) is the template of the ensenmble-based graph analysis using connectivity directed data.
ensemble

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity directed/_AnalyzeEnsemble_CON_WD.gen.m
> +ID (data, string) is a few-letter code for the ensenmble-based graph analysis using connectivity directed data.
ensemble

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity directed/_AnalyzeEnsemble_CON_WD.gen.m
> +LABEL (metadata, string) is an extended label of the ensenmble-based graph analysis using connectivity directed data.
ensemble

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity directed/_AnalyzeEnsemble_CON_WD.gen.m
> +NOTES (metadata, string) are some specific notes about the ensenmble-based graph analysis using connectivity directed data.
ensemble

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/connectivity/_ImporterGroupSubjectCON_XLS.gen.m
> +ELCLASS (constant, string) is the class of the CON subject group importer from XLS/XLSX.
in some descriptions there is "... from XLS/XLSX" and in others there is "... from XLSX" or "... from XLS"

2023-10-27 08:36 UTC, bzufiriaki commented on braph2genesis/pipelines/structural/_AnalyzeGroup_ST_BUD.gen.m
> +ELCLASS (constant, string) is the class of the group-based graph analysis with structural data at fixed density.
sometimes is "**at** fixed density" and other times is "**of** fixed density"

2023-10-30 13:11 UTC, hanzh346 commented on braph2genesis/pipelines/structural multiplex/_ImporterGroupSubjectST_MP_XLS.gen.m
> +ELCLASS (constant, string) is the class of the ST MP subject group importer from XLS/XLSX.
Should we use the full name "structural multiplex" on "ST MP", also it applies to other descriptions relevant.

2023-10-31 13:29 UTC, merged