Update BRAPH2GUI.m
softmatterlab/BRAPH-2-Matlab pull request #1688
Opened 2023-10-30 12:13 UTC by egolol

It look better now
![image](https://github.com/braph-software/BRAPH-2/assets/15255163/5d27b632-9313-45c8-a1e6-889df8bb805c)

2023-10-30 13:07 UTC, c-yuwei approved these changes

2023-10-30 13:07 UTC, iok-ui commented on braph2genesis/src/gui/BRAPH2GUI.m
> +
is there any particular reason to leave no space between "=" and "0.0025" the number?

2023-10-30 13:09 UTC, egolol commented on braph2genesis/src/gui/BRAPH2GUI.m
> +
no

2023-10-30 13:54 UTC, hanzh346 approved these changes

2023-10-31 12:38 UTC, giovannivolpe requested changes
Add button to open JSON files

2023-11-03 13:36 UTC, merged